apiVersion: v1                 # Menunjukkan kubernetes api version yang digunakan
kind: Secret                   # Kind/tipe dari resource yang digunakan yaitu secret yang digunakan untuk menyimpan secret data seperti credentials
metadata:                      # Menunjukkan metada yang akan digunakan oleh configmap
  name: mongo-secret           # Nama dari secret
stringData:                    # Digunakan untuk menambahkan data berupa string yang mana berupa plain text
  MONGO_ROOT_USERNAME: admin
data:                          # Digunakan untuk menambahkan data berupa base64 encode yang mana proses decode akan dilakukan oleh kubernetes
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==