# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  go : circleci/go@1.8.0

jobs:
  lint-dockerfile:
    executor:
      name: docker/hadolint
      tag: 'v2.12.1-beta-debian'
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  test-app:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Test Go App
          command: go test -v -short --count=1 $(go list ./...)

  build-karsajobs:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push image
          command: |
            docker build -t karsajobs:latest .
            docker tag karsajobs:latest ghcr.io/gonewajetiket/karsajobs:latest
            export CR_PAT=YOUR_GITHUB_TOKEN
            echo $CR_PAT | docker login ghcr.io -u GonewajeTiket --password-stdin
            docker push ghcr.io/gonewajetiket/karsajobs:latest


workflows:
  main:
    jobs:
      - lint-dockerfile
      - test-app
      - build-karsajobs