# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
# jobs:
#   lint-dockerfile:
#     # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
#     # See: https://circleci.com/docs/configuration-reference/#executor-job
orbs:
  docker: circleci/docker@2.2.0
  go : circleci/go@1.8.0

jobs:
  test-app:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
          name: Test Go App
          command: go test -v -short --count=1 $(go list ./...)

workflows:
  main:
    jobs:
      - docker/hadolint:
          dockerfiles: Dockerfile
          executor-class: medium
          hadolint-tag: 2.2.0-debian
          ignore-rules: DL4005,DL3008
          trusted-registries: docker.io
      - test-app