# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1                                # Konfigurasi pipeline circleci menggunakan spesifik versi 2.1

orbs:                                       # Menggunakan orbs yaitu reusabale packages dari circleci config
  docker: circleci/docker@2.2.0             # Menggunakan docker orbs untuk task yang berhubungan dengan docker
  go : circleci/go@1.8.0                    # Menggunakan docker orbs untuk task yang berhubungan dengan bahasa go

jobs:                                       # Mendifinisikan job yang ada dan digunakan
  lint-dockerfile:                          # Judul atau title dari job
    executor:                               # Menunjukkan bahwa jobs menggunakan executor
      name: docker/hadolint                 # Job menggunakan executor docker dengan image hadolint
      tag: 'v2.12.1-beta-debian'            # Tag dari docker image hadolint yang digunakan yaitu v2.12.1-beta-debian
    steps:                                  # Urutan step atau langkah-langkah yang akan dijalankan dari job lint-dockerfile
      - checkout                            # Melakukan perintah checkout dari repository
      - setup_remote_docker                 # Menggunakan remote docker environment, dimana tiap command 'docker' akan dieksekusi secara lokal di vm yang digunakan untuk menjalankan container docker utama
      - run:                                # Menjalankan atau mengeksekusi sebuah perintah/command
          name: Lint Dockerfile             # Nama dari perintah ataupun eksekusi yang akan dijalankan
          command: hadolint Dockerfile      # Command yang akan dijalankan yaitu hadolint Dockerfile (nama dockerfile)

  test-app:                                 # Judul atau title dari job
    executor:                               # Menunjukkan bahwa jobs menggunakan executor
      name: go/default                      # Job menggunakan executor go dengan image default
      tag: '1.16'                           # Tag dari go image yang digunakan yaitu 1.16
    steps:                                  # Urutan step atau langkah-langkah yang akan dijalankan dari job test-app
      - checkout                            # Melakukan perintah checkout dari repository
      - go/load-cache                       # Melakukan proses load go module cache apabila tersedia untuk mempercepat proses build
      - go/mod-download                     # Download go modul
      - go/save-cache                       # Menyimpan cache dari go module yang kemudian dapat digunakan untuk proses build selanjutnya
      - run:                                # Menjalankan atau mengeksekusi sebuah perintah/command
          name: Test Go App                 # Nama dari perintah ataupun eksekusi yang akan dijalankan
          command: go test -v -short --count=1 $(go list ./...)       # Command yang akan dijalankan yaitu perintah go test yang akan melakukan testing terhadap file _test.go

  build-karsajobs:                          # Judul atau title dari job
    docker:                                 # Eksekutor yang digunakan adalah docker
      - image: cimg/base:current            # Docker image yang digunakan adalah cimg/base dengan versi current
    steps:                                  # Urutan step atau langkah-langkah yang akan dijalankan dari job test-app
      - checkout                            # Melakukan perintah checkout dari repository
      - setup_remote_docker                 # Menggunakan remote docker environment, dimana tiap command 'docker' akan dieksekusi secara lokal di vm yang digunakan untuk menjalankan container docker utama
      - run:                                # Menjalankan atau mengeksekusi sebuah perintah/command
          name: Build and push image        # Nama dari perintah ataupun eksekusi yang akan dijalankan
          command: |                        # Perintahkan yang akan dijalankan, karena terdapat banyak command makan digunakan tanda pipe |
            docker build -t karsajobs:latest .
            docker tag karsajobs:latest ghcr.io/gonewajetiket/karsajobs:latest
            export CR_PAT=YOUR_GITHUB_TOKEN
            echo $CR_PAT | docker login ghcr.io -u GonewajeTiket --password-stdin
            docker push ghcr.io/gonewajetiket/karsajobs:latest


workflows:                                  # Menunjukkan workflow ataupun urutan job yang akan dijalankan
  build-karsajobs:                          # Judul dari workflow
    jobs:                                   # Daftar job yang akan dijalankan dari workflow dan akan dieksekusi secara berurutan
      - lint-dockerfile
      - test-app
      - build-karsajobs