apiVersion: v1                 # Menunjukkan kubernetes api version yang digunakan
kind: Namespace                # Kind/tipe dari resource yang digunakan yaitu namespace
metadata:                      # Menunjukkan metada yang akan digunakan oleh namespace
  name: ecommerce-ns           # Nama dari object namespace
  labels:                      # Label dari object namespace
    app: ecommerce