apiVersion: v1                 # Menunjukkan kubernetes api version yang digunakan
kind: Secret                   # Kind/tipe dari resource yang digunakan yaitu secret yang digunakan untuk menyimpan secret data seperti credentials
metadata:                      # Menunjukkan metada yang akan digunakan oleh configmap
  name: rabbitmq-secret        # Nama dari secret
  namespace: ecommerce-ns      # Mengarahkan object ke namespace 'ecommerce-ns'
data:                          # Digunakan untuk menambahkan data berupa base64 encode yang mana proses decode akan dilakukan oleh kubernetes
  RABBITMQ_HOST_PASSWORD: YW1xcDovL2d1ZXN0Omd1ZXN0QHJhYmJpdG1xOjU2NzI=