apiVersion: v1                 # Menunjukkan kubernetes api version yang digunakan
kind: Service                  # Kind/tipe dari resource yang digunakan yaitu service
metadata:                      # Menunjukkan metada yang akan digunakan oleh service
  name: shipping-svc           # Nama dari service
  namespace: ecommerce-ns      # Mengarahkan object ke namespace 'ecommerce-ns'
  labels:                      # Memberikan label dari service yaitu key app dengan value microservices
    app: microservices
spec:                          # Menunjukkan spesifikasi dari service
  type: NodePort               # Menunjukkan tipe dari service adalah nodeport dimana service akan diekspose pada tiap node dicluster dan dapat diakses menggunakan node ip dan node port
  selector:                    # Menunjukkan bagaimana service dikelompokkan berdasarkan label dengan key tier dan value shipping
    tier: shipping
  ports:                       # Menunjukkan port yang terbuka untuk service
    - port: 3001               # Port yang akan dilisten oleh service
      targetPort: 3001         # Port yang akan memforward traffic oleh service
      nodePort: 31111          # Memberikan spesifik port yang akan diopen ditiap node sehingga dapat diakses pada pod tersebut
